# Generated by Django 4.2.23 on 2025-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltyrule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loyaltyrule",
            name="config",
            field=models.JSONField(
                default=dict,
                help_text='JSON configuration for the trigger (e.g., {"threshold": 100})',
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyrule",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="loyaltyrule",
            name="reward",
            field=models.JSONField(
                default=dict,
                help_text='JSON configuration for the reward (e.g., {"type": "POINTS", "amount": 10})',
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyrule",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("SPEND_BASED", "Spend-Based"),
                    ("ORDER_FREQUENCY", "Order Frequency"),
                    ("FIRST_ORDER", "First Order"),
                    ("REFERRAL", "Referral"),
                    ("BIRTHDAY_BONUS", "Birthday Bonus"),
                    ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                ],
                help_text="The event that triggers this rule.",
                max_length=50,
            ),
        ),
    ]
