# Generated by Django 4.2.23 on 2025-07-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parameters used to generate this report",
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Generated report data"),
                ),
                (
                    "export_formats",
                    models.JSONField(
                        default=list,
                        help_text="List of formats this report was exported to",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("generation_time", models.DurationField(blank=True, null=True)),
                (
                    "data_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size in bytes", null=True
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this report cache expires",
                        null=True,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily_sales", "Daily Sales Report"),
                            ("monthly_profit", "Monthly Profitability Report"),
                            ("customer_statement", "Customer Statement"),
                            ("expense_summary", "Expense Summary"),
                            ("service_analysis", "Service Analysis"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Report configuration including filters, columns, etc.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all users can access this template",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles that can access this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["report_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("run_time", models.TimeField(default="09:00:00")),
                ("timezone", models.CharField(default="Africa/Lagos", max_length=50)),
                (
                    "email_recipients",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses to send reports to",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Default parameters for scheduled reports",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_schedules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("last_downloaded", models.DateTimeField(blank=True, null=True)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="reports.generatedreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Export",
                "verbose_name_plural": "Report Exports",
                "ordering": ["-exported_at"],
            },
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["template", "-generated_at"],
                name="reports_gen_templat_9e850a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["generated_by", "-generated_at"],
                name="reports_gen_generat_e2bb98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(fields=["status"], name="reports_gen_status_b3120a_idx"),
        ),
    ]
