# Generated by Django 4.2.23 on 2025-07-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMergeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merged_customer_name", models.CharField(max_length=200)),
                ("merged_customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "merged_customer_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("merged_customer_address", models.TextField(blank=True)),
                ("merged_orders_count", models.PositiveIntegerField(default=0)),
                ("merged_notes_count", models.PositiveIntegerField(default=0)),
                ("merge_reason", models.TextField(blank=True)),
                ("merged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_merges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_history_as_primary",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Merge History",
                "verbose_name_plural": "Customer Merge Histories",
                "ordering": ["-merged_at"],
            },
        ),
    ]
