# Generated by Django 4.2.23 on 2025-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customermergehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Customer's date of birth for birthday rewards.",
                null=True,
            ),
        ),
    ]
