# Generated by Django 4.2.23 on 2025-07-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="loyalty_points",
            field=models.PositiveIntegerField(
                default=0, help_text="Current loyalty points balance."
            ),
        ),
    ]
