# Generated by Django 4.2.23 on 2025-07-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0002_paymentmethod"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method_legacy",
            field=models.CharField(
                blank=True,
                help_text="Legacy payment method field for migration purposes",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                help_text="Payment method used for this order",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="system_settings.paymentmethod",
            ),
        ),
    ]
