# Generated by Django 4.2.23 on 2025-07-02 12:06

from django.db import migrations


def migrate_payment_methods(apps, schema_editor):
    """Migrate existing payment methods to the new PaymentMethod model"""
    Order = apps.get_model('orders', 'Order')
    PaymentMethod = apps.get_model('system_settings', 'PaymentMethod')
    
    # Create a mapping from old payment method codes to PaymentMethod instances
    payment_method_mapping = {}
    
    # Get or create PaymentMethod instances for each unique payment method in orders
    for order in Order.objects.all():
        if hasattr(order, 'payment_method_legacy') and order.payment_method_legacy:
            old_payment_method = order.payment_method_legacy
            
            # If we haven't processed this payment method code yet
            if old_payment_method not in payment_method_mapping:
                # Try to find an existing PaymentMethod with this code
                try:
                    payment_method = PaymentMethod.objects.get(code=old_payment_method)
                    payment_method_mapping[old_payment_method] = payment_method
                except PaymentMethod.DoesNotExist:
                    # Create a default PaymentMethod for this code
                    payment_method_name = old_payment_method.replace('_', ' ').title()
                    payment_method = PaymentMethod.objects.create(
                        code=old_payment_method,
                        name=payment_method_name,
                        description=f'Migrated from legacy payment method: {old_payment_method}',
                        is_active=True,
                        sort_order=99  # Put migrated methods at the end
                    )
                    payment_method_mapping[old_payment_method] = payment_method
            
            # Update the order's payment_method foreign key
            order.payment_method = payment_method_mapping[old_payment_method]
            order.save(update_fields=['payment_method'])


def reverse_migrate_payment_methods(apps, schema_editor):
    """Reverse migration - copy payment method names back to legacy field"""
    Order = apps.get_model('orders', 'Order')
    
    for order in Order.objects.all():
        if order.payment_method:
            order.payment_method_legacy = order.payment_method.code
            order.save(update_fields=['payment_method_legacy'])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_method_legacy_and_more"),
        ("system_settings", "0002_paymentmethod"),
    ]

    operations = [
        migrations.RunPython(
            migrate_payment_methods,
            reverse_migrate_payment_methods
        ),
    ]
