# Generated by Django 4.2.23 on 2025-07-04 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="loyalty_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Discount applied from loyalty points",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="redeemed_points",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of loyalty points redeemed for this order"
            ),
        ),
    ]
